config/routes.rb
Website::Application.routes.draw do

  root 'home#index'

  post 'users/sign_in' => 'users#sign_in'
  post 'users/sign_out' => 'users#sign_out'
  get 'users/dashboard' => 'users#dashboard'
  get 'users/profile/:id' => 'users#profile'
  get 'users/new' => 'users#new'
  get 'donations/new' => 'donations#new'
	get 'donations/edit/:id' => 'donations#edit'
	post 'donations/edit_donation' => 'donations#edit_donation'
  post 'donations/create_donation' => 'donations#create_donation'
	post 'donations/delete' => 'donations#delete'
  post 'users/update_profile' => 'users#update_profile'
  post 'users/create_user' => 'users#create_user'
  get 'users/find_users' => 'users#find_users'
  get 'users/search' => 'users#search'
  get 'donations/search' => 'donations#search'
  get 'donation/export' => 'donations#export'
  get 'users/forgot_password' => 'users#forgot_password'
  get 'send_email' => 'users#send_email'
	post 'users/upload_profile_pic' => 'users#upload_profile_pic'
	get 'users/change_password' => 'users#change_password'
	post 'users/change_password_action' => 'users#change_password_action'
	post 'users/reset_password' => 'users#reset_password'
	get 'request_reset_password' => 'home#request_reset_password'
	post 'users/change_admin' => 'users#change_admin'

	get 'api/authentication_token' => 'api#authentication_token'
	get 'api/donation/:id' => 'api#donation'
	get 'api/user/:id' => 'api#user'
	get	'api/profile/:id' => 'api#profile'
	get	'api/recent/users' => 'api#recent_users'
	get	'api/recent/donations' => 'api#recent_donations'
	get	'api/search/users' => 'api#search_users'
	get	'api/report/users' => 'api#report_users'
	get	'api/report/donations' => 'api#report_donations'
	
	post 'api/login' => 'api#login'
	post 'api/logout' => 'api#logout'
	post 'api/forgot_password' => 'api#forgot_password'
	post 'api/edit/password/:id' => 'api#edit_password'
	post 'api/edit/profile/:id' => 'api#edit_profile'
	post 'api/edit/profile_pic/:id' => 'api#edit_profile_pic'
	post 'api/new/user' => 'api#new_user'
	post 'api/new/donation' => 'api#new_donation'
	post 'api/edit/administratorship/:id' => 'api#edit_administratorship'
	post 'api/edit/donation/:id' => 'api#edit_donation'
	post 'api/delete/donation/:id' => 'api#delete_donation'

end

app/models/donation.rb
class Donation < ActiveRecord::Base
	#has_one :currency
	belongs_to :currency
	belongs_to :user
	belongs_to :admin, :class_name => 'User', :foreign_key => 'admin_id'

	def self.to_csv(options = {})
		CSV.generate(options) do |csv|
			csv << column_names
			all.each do |donation|
				csv << donation.attributes.values_at(*column_names)
			end
		end
	end

end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
	def new
		@currencies = []
		@donations = []
		begin
			session_user_id = session["user_id"]
			session_user = User.find_by_id(session_user_id)

			if session_user
				if session_user.authentication
					if ((DateTime.now() - session_user.authentication.issued_at.to_datetime()) * 24 * 60).to_i <= 15
						session_user.authentication.issued_at = DateTime.now()
						session_user.authentication.save()

						@currencies = Currency.all
						@donations = Donation.find_by_sql(["select d.*, a.fullname as received_by, u.fullname from donations d inner join users a on a.id = d.admin_id inner join users u on u.id = d.user_id where d.created_at >= now() - INTERVAL 1 DAY"])
					else
						flash["alert"] = "Your session is expired. Please try login again."
						flash["type"] = "warning"

						reset_session
					end
				else
					flash["alert"] = "Your session is expired. Please try login again."
					flash["type"] = "warning"

					reset_session
				end
			else
				reset_session
			end
		rescue
			logger.error "#{$!}"
			logger.debug "#{$@}"
		end
	end

	def edit
		@currencies = []
		@donations = []
		donation_id = params["id"]
		begin
			session_user_id = session["user_id"]
			session_user = User.find_by_id(session_user_id)

			if session_user
				if session_user.authentication
					if ((DateTime.now() - session_user.authentication.issued_at.to_datetime()) * 24 * 60).to_i <= 15
						session_user.authentication.issued_at = DateTime.now()
						session_user.authentication.save()

						@currencies = Currency.all
						@donation = Donation.find_by_id(donation_id)
						@donations = Donation.find_by_sql(["select d.*, a.fullname as received_by, u.fullname from donations d inner join users a on a.id = d.admin_id inner join users u on u.id = d.user_id where d.created_at >= now() - INTERVAL 1 DAY"])
					else
						flash["alert"] = "Your session is expired. Please try login again."
						flash["type"] = "warning"

						reset_session
					end
				else
					flash["alert"] = "Your session is expired. Please try login again."
					flash["type"] = "warning"

					reset_session
				end
			else
				reset_session
			end
		rescue
			logger.error "#{$!}"
			logger.debug "#{$@}"
		end
	end

	def delete
		response_data = {}
		response_data["result"] = "failed"

		begin
			session_user_id = session["user_id"]
			session_user = User.find_by_id(session_user_id)

			if session_user
				if session_user.authentication
					if ((DateTime.now() - session_user.authentication.issued_at.to_datetime()) * 24 * 60).to_i <= 15
						session_user.authentication.issued_at = DateTime.now()
						session_user.authentication.save()

						donation_id = params[:donation_id]
						donation = Donation.find_by_id(donation_id)
						
						if donation
							logger.info "Deleting donation"
							logger.info "id=#{donation.id}"
							logger.info "user_id=#{donation.user_id}"
							logger.info "received_date=#{donation.received_date}"
							logger.info "amount=#{donation.amount}"
							logger.info "currency_id=#{donation.currency_id}"
							logger.info "remark=#{donation.remark}"
							logger.info "admin_id=#{donation.admin_id}"
							logger.info "created_at=#{donation.created_at}"
							logger.info "updated_at=#{donation.updated_at}"
							logger.info "deleted_by=#{request.session['user_id']}"

							donation.delete()

							response_data["result"] = "successful"
						else
							response_data["message"] = "Donation not found"
						end
					else
						flash["alert"] = "Your session is expired. Please try login again."
						flash["type"] = "warning"

						reset_session
					end
				else
					flash["alert"] = "Your session is expired. Please try login again."
					flash["type"] = "warning"

					reset_session
				end
			else
				reset_session
			end
		rescue
			logger.error "#{$!}"
			logger.debug "#{$@}"

			response_data["result"] = "failed"
			response_data["message"] = "Error"
		end

		render :json => response_data and return
	end

	def edit_donation
		ActiveRecord::Base.transaction do
			donation_id = ""
			begin
				session_user_id = session["user_id"]
				session_user = User.find_by_id(session_user_id)

				if session_user
					if session_user.authentication
						if ((DateTime.now() - session_user.authentication.issued_at.to_datetime()) * 24 * 60).to_i <= 15
							session_user.authentication.issued_at = DateTime.now()
							session_user.authentication.save()

							logger.debug "#{params.to_json}"

							donation_id = params[:donation_id]
							amount = params[:amount]
							currency_id = params[:currency]
							received_date = params[:received_date]
							remark = params[:remark]

							donation = Donation.find_by_id(donation_id)

							if donation

								logger.info "Editing donation"
								logger.info "id=#{donation.id}"
								logger.info "user_id=#{donation.user_id}"
								logger.info "received_date=#{donation.received_date}"
								logger.info "amount=#{donation.amount}"
								logger.info "currency_id=#{donation.currency_id}"
								logger.info "remark=#{donation.remark}"
								logger.info "admin_id=#{donation.admin_id}"
								logger.info "created_at=#{donation.created_at}"
								logger.info "updated_at=#{donation.updated_at}"
								logger.info "edited_by=#{request.session['user_id']}"

								donation.amount = amount
								donation.currency_id = currency_id
								donation.received_date = received_date
								donation.remark = remark

								donation.save()

								flash["alert"] = "Donation has been edited."
								flash["type"] = "success"

								redirect_to "/donations/edit/#{donation_id}" and return
							else
								flash["alert"] = "Donation not found."
								flash["type"] = "warning"

								redirect_to donations_search_path and return
							end

						else
							flash["alert"] = "Your session is expired. Please try login again."
							flash["type"] = "warning"

							reset_session
						end
					else
						flash["alert"] = "Your session is expired. Please try login again."
						flash["type"] = "warning"

						reset_session
					end
				else
					reset_session
				end
			rescue
				logger.error "#{$!}"
				logger.debug "#{$@}"

				flash["alert"] = "Sorry, cannot edit donation."
				flash["type"] = "warning"				
				ActiveRecord::Rollback
			end
		end

		redirect_to donations_search_path and return
	end

	def create_donation
		ActiveRecord::Base.transaction do
			begin
				session_user_id = session["user_id"]
				session_user = User.find_by_id(session_user_id)

				if session_user
					if session_user.authentication
						if ((DateTime.now() - session_user.authentication.issued_at.to_datetime()) * 24 * 60).to_i <= 15
							session_user.authentication.issued_at = DateTime.now()
							session_user.authentication.save()

							logger.debug "#{params.to_json}"

							selected = params[:selected]
							admin_id = session["user_id"]
							user_id = params[:user_id]
							amount = params[:amount]
							currency_id = params[:currency]
							received_date = params[:received_date]
							remark = params[:remark]

							if selected == 'true'
								Donation.create(:user_id => user_id,
									:received_date => received_date,
									:amount => amount,
									:currency_id => currency_id,
									:remark => remark,
									:admin_id => admin_id)

								flash["alert"] = "New donation has been submitted."
								flash["type"] = "success"

								donation = Donation.last

								superuser_emails = User.where(['is_super_admin=1']).pluck(:email)
								admin_id = session["user_id"]
								admin = User.find_by_id(admin_id)
								superuser_emails << admin.email

								UserMailer.new_donation(donation, superuser_emails).deliver
							else
								flash["alert"] = "Failed to submit new donation. Please check your data."
								flash["type"] = "warning"
							end

						else
							flash["alert"] = "Your session is expired. Please try login again."
							flash["type"] = "warning"

							reset_session
						end
					else
						flash["alert"] = "Your session is expired. Please try login again."
						flash["type"] = "warning"

						reset_session
					end
				else
					reset_session
				end
				
			rescue
				logger.error "#{$!}"
				logger.debug "#{$@}"

				flash["alert"] = "Sorry, cannot submit donation."
				flash["type"] = "warning"				
				ActiveRecord::Rollback
			end
		end

		redirect_to donations_new_path and return
	end

	def search
		@donations = []

		begin
			session_user_id = session["user_id"]
			session_user = User.find_by_id(session_user_id)

			if session_user
				if session_user.authentication
					if ((DateTime.now() - session_user.authentication.issued_at.to_datetime()) * 24 * 60).to_i <= 15
						session_user.authentication.issued_at = DateTime.now()
						session_user.authentication.save()

						@donations = Donation.all

					else
						flash["alert"] = "Your session is expired. Please try login again."
						flash["type"] = "warning"

						reset_session
					end
				else
					flash["alert"] = "Your session is expired. Please try login again."
					flash["type"] = "warning"

					reset_session
				end
			else
				reset_session
			end
		rescue
			logger.error "#{$!}"
			logger.debug "#{$@}"
		end
	end

  def export
    @donations = []
    begin
      session_user_id = session["user_id"]
      session_user = User.find_by_id(session_user_id)

      if session_user
        if session_user.authentication
          if ((DateTime.now() - session_user.authentication.issued_at.to_datetime()) * 24 * 60).to_i <= 15
            session_user.authentication.issued_at = DateTime.now()
            session_user.authentication.save()

						currencyquery = Currency.select('id,currency as curr').to_sql
						userquery = User.select('id, fullname, nickname').to_sql

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/edit.html.erb
<script>
	$(document).ready(function() {
		$('#t_received_date').datepicker({
			dateFormat: "yy-mm-dd"
			/*yearRange : 'yy-50:yy+1'
			format: "yyyy-mm-dd",
			weekStart: 0,
			startDate: "1987-01-01",
			endDate: "1988-01-01",
			todayBtn: "linked",
			multidate: false
			*/
		});
	});
</script>
<div class="row component">
	<div class="col-md-12">
		<form id="f_donation" action="/donations/edit_donation" method="post">
			<input type="hidden" name="donation_id" value="<%= @donation.id %>">
			<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>"/>
			
			<input type="hidden" name="user_id" id="user_id">

			<label for="t_fullname">Donor Name</label>
			<input type="text" id="t_fullname" name="fullname" class="form-control" onkeyup="findUsers(event)" autocomplete="off" value="<%= @donation.user.fullname %>" readonly> <br/>
			
			<label for="t_amount">Amount</label>
			<input type="text" id="t_amount" name="amount" class="form-control" value="<%= @donation.amount %>">
			<br/>
			<label>Currency</label>
			<select id="s_currency" name="currency" class="form-control" style="width: 100px;">
			<% for currency in @currencies %>
				<% if currency.id == @donation.currency_id %>
					<option value="<%= currency.id %>" selected><%= currency.currency%></option>
				<% else %>
					<option value="<%= currency.id %>"><%= currency.currency%></option>
				<% end %>
			<% end %>
			</select>
			<br/>

			<label for="t_received_date">Received Date (yyyy-mm-dd)</label>
			<input type="text" id="t_received_date" name="received_date" class="form-control" value="<%= @donation.received_date %>"> <br/>
	
			<label>Remark</label>
			<textarea id="t_remark" name="remark" class="form-control"><%= @donation.remark %></textarea><br/>
			
			<button type="submit" class="btn btn-primary" id="b_edit"> Edit </button>
		</form>
	</div>
<div>
<div class="row">
	<div class="col-md-12">
		<h3> Recently added donations </h3>
		<table id="donation_table" border="3">
			<thead>
				<tr>
					<th>Trans. No</th>
					<th>Donor Name</th>
					<th>Amount</th>
					<th>Currency</th>
					<th>Received Date</th>
					<th>Remark</th>
					<th>Received By</th>
				</tr>
			</thead>
			<% @donations.each do |donation| %>
			<tbody>	
				<tr>
					<td><%= donation.id %></td>
					<td><%= donation.user.fullname %></td>
					<td><%= donation.amount %></td>
					<td><%= donation.currency.currency %></td>
					<td><%= donation.received_date %></td>
					<td><%= donation.remark %></td>
					<td><%= donation.admin.fullname %></td>
				</tr>
			</tbody>
			<% end %>
		</table>
	</div>
</div>


app/views/donations/new.html.erb
<script>
	$(document).ready(function() {
		$('#t_received_date').datepicker({
			dateFormat: "yy-mm-dd"
			/*yearRange : 'yy-50:yy+1'
			format: "yyyy-mm-dd",
			weekStart: 0,
			startDate: "1987-01-01",
			endDate: "1988-01-01",
			todayBtn: "linked",
			multidate: false
			*/
		});
	});

	function findUsers(event) {

		if(event.keyCode == 13 || event.keyCode == 38 || event.keyCode == 40)
			return;

		var text = $('#t_fullname').val();
		console.log(text);
		$('#selected').val("false");

		$.ajax({
			type:"GET",
			url:"/users/find_users?seed=" + text,
			success: function(data) {
				var availableNames = data.names;
				var availableIds = data.ids;

				console.log(availableNames);
				console.log(availableIds);

				$("#t_fullname").autocomplete({
					source: availableNames,
					select: function (event, ui) {
						console.log(event.originalEvent);	
						$('#selected').val("true");
						var data = ui.item.value;
						var id = data.split(',')[0];
						$('#user_id').val(id);
					}
				});
			},
			error: function() {
			       
			}
		});
	};

	function submitDonation() {
		var selected = $('#selected').val();
		if(selected == "true") {
			$('#f_donation').submit();
		}
	}
  </script>
<div class="row component">
	<div class="col-md-12">
		<form id="f_donation" action="/donations/create_donation" method="post">
			<input type="hidden" name="selected" id="selected" value="false">
			<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>"/>
			
			<input type="hidden" name="user_id" id="user_id">

			<label for="t_fullname">Donor Name</label>
			<input type="text" id="t_fullname" name="fullname" class="form-control" onkeyup="findUsers(event)" autocomplete="off"> <br/>
			
			<label for="t_amount">Amount</label>
			<input type="text" id="t_amount" name="amount" class="form-control">
			<br/>
			<label>Currency</label>
                        <select id="s_currency" name="currency" class="form-control" style="width: 100px;">
				<% for currency in @currencies %>
					<option value="<%= currency.id %>"><%= currency.currency%></option>
                                <% end %>
                        </select>
                        <br/>

			<label for="t_received_date">Received Date (yyyy-mm-dd)</label>
			<input type="text" id="t_received_date" name="received_date" class="form-control"> <br/>
	
			<label>Remark</label>
			<textarea id="t_remark" name="remark" class="form-control"></textarea><br/>
			
			<button type="button" class="btn btn-primary" id="b_save" onclick="submitDonation()"> Save </button>
		</form>
	</div>
<div>
<div class="row">
	<div class="col-md-12">
		<h3> Recently added donations </h3>
		<table id="donation_table" border="3">
			<thead>
				<tr>
					<th>Trans. No</th>
					<th>Donor Name</th>
					<th>Amount</th>
					<th>Currency</th>
					<th>Received Date</th>
					<th>Remark</th>
					<th>Received By</th>
				</tr>
			</thead>
			<% @donations.each do |donation| %>
			<tbody>	
				<tr>
					<td><%= donation.id %></td>
					<td><%= donation.user.fullname %></td>
					<td><%= donation.amount %></td>
					<td><%= donation.currency.currency %></td>
					<td><%= donation.received_date %></td>
					<td><%= donation.remark %></td>
					<td><%= donation.admin.fullname %></td>
				</tr>
			</tbody>
			<% end %>
		</table>
	</div>
</div>


app/views/donations/search.html.erb
<script>
	$(document).ready(function() {

		$(".edit_donation").click(function () {
			var donation_id = $(this).attr('value');
			window.location.href = "/donations/edit/" + donation_id;
		});

		$(".delete_donation").click(function () {
			var result = confirm("Are you sure to delete this donation?");
			if (result == true) {
				var donation_id = $(this).attr('value');
				
				$.ajax({
					type:"POST",
					url:"/donations/delete",
					beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
					dataType: "json",
					data: { "donation_id" : donation_id },
					success: function(data) {
						if(data.result == 'successful') {
							location.reload();
						}
						else {
							alert(data.message);
						}
					},
					error: function() {
						console.log("error");			 
					}
				});
			}
		});
	});
</script>

<div class="row component">
	<div class="col-md-12">
		<h3> Donations </h3>
        <div class="edit btn btn-default" style="margin-bottom:5px"><%= link_to "Export CSV", donation_export_path(format: "csv") %></div>
		<table id="donation_table" border="3">
			<thead>
				<tr>
					<th>Trans. No</th>
					<th>Donor Name</th>
					<th>Amount</th>
					<th>Currency</th>
					<th>Received Date</th>
					<th>Remark</th>
					<th>Received By</th>
					<% if request.session["is_super_admin"] == true %>
					<th>Edit</th>
					<th>Delete</th>
					<% end %>
				</tr>
			</thead>
			<tbody>
			<% @donations.each do |donation| %>
				<tr class="table_body">
					<td><%= donation.id %></td>
					<td><%= donation.user.fullname %> (<%= donation.user.member_no %>)</td>
					<td><%= donation.amount %></td>
					<td><%= donation.currency.currency %></td>
					<td><%= donation.received_date %></td>
					<td><%= donation.remark %></td>
					<td><%= donation.admin.fullname %></td>
					<% if request.session["is_super_admin"] == true %>
						<td><a href="#" class="edit_donation" value='<%= donation.id %>' id='l_edit_<%= donation.id %>'>Edit</a></td>
						<td><a href="#" class="delete_donation" value='<%= donation.id %>' id='l_delete_<%= donation.id %>'>Delete</a></td>
					<% end %>
				</tr>
			<% end %>
			</tbody>
		</table>
	</div>
</div>
